# Uncomment this line to define a global platform for your project
platform :ios, '8.1'
# Uncomment this line if you're using Swift
use_frameworks!

target 'MSTripPlanner' do
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'GoogleMaps'
    pod 'Gloss', '~> 0.6'
end

target 'MSTripPlannerTests' do

end

target 'MSTripPlannerUITests' do

end
